### ISSUE TITLE
可以提供epub格式么，感谢作者

### ISSUE THREAD

**Issue by colinwjd** [johnlui/PPHC#18]

**Comment by pifeifei** [comment]
pandoc 和 gitbook 可以转换， 只是有一定的格式要求

请问是否可以进行编辑以适配呢？

**Comment by johnlui** [comment]
完整版十四万多字的出版文稿已经写完，已经放到了独立网站上：https://pphc.lvwenhan.com  网站右上角提供 pdf 下载链接，epub 版可能需要你自己制作了，在不违反“[署名—非商业性使用—禁止演绎 4.0 协议](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.zh-Hans)”的情况下，可以任意进行分发
