### ISSUE TITLE
已推荐，格式问题往修复

### ISSUE THREAD

**Issue by Snailclimb** [johnlui/PPHC#2]
前段时间看到老哥的文章，看的津津有味，收益良多，已推荐。

Github 项目这里阅读格式存在问题，另外，建议 README 中给一下文章的直达地址。

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/29880145/218668391-7dd7bbbb-948d-4a70-a324-f395bdbfe75e.png">

**Comment by johnlui** [comment]
马上修复

**Comment by johnlui** [comment]
搞定

**Comment by Snailclimb** [comment]
> 马上修复

辛苦了 大佬，感恩ღ( ´･ᴗ･` )比心
