### ISSUE TITLE
是否有文字错误

### ISSUE THREAD

**Issue by BigTailMonkey** [johnlui/PPHC#4]
![image](https://user-images.githubusercontent.com/23235309/219021109-9046c394-edbe-4773-aa68-957b6dfd1368.png)

**Comment by johnlui** [comment]
已经修正，感谢反馈

**Comment by BigTailMonkey** [comment]
![image](https://user-images.githubusercontent.com/23235309/219247811-6042bd09-6ecd-4f96-846f-15601386016c.png)
还有一个在第八章InnoDB中。

**Comment by johnlui** [comment]
优秀啊，已经修复

**Comment by BigTailMonkey** [comment]
还有一个哦。
![image](https://user-images.githubusercontent.com/23235309/219290277-3dd5cbf9-b2c2-4bd6-a944-e2f3b4365628.png)
通读全篇，豁然开朗。没看之前也为很多事情苦恼：单个MySQL实例能支撑业务发展到什么程度；什么时候要进行分表；什么时候要引入分布式事务……类似于以上种种。搜寻良久也没有找到心目中的答案。通过您写的这本“小书”，让我有了更清晰的认识。感谢！

**Comment by johnlui** [comment]
优秀👍
