### ISSUE TITLE
是否可以提供更友好的在线阅读方式

### ISSUE THREAD

**Issue by Elitedj** [johnlui/PPHC#6]
好书已收藏！

但是是否可以提供像git book一样的更加友好的在线阅读方式呢？感谢

**Comment by yswtrue** [comment]
一样，希望可以用gitbook来展示

**Comment by johnlui** [comment]
一共只有 10 篇文章，点进对应的目录，就能直接阅读了，不需要什么高级的展示方法，如果想在网页上阅读，可以看我的网站 https://lvwenhan.com/tech-epic/499.html

**Comment by yswtrue** [comment]
非常感谢

**Comment by Elitedj** [comment]
> 一共只有 10 篇文章，点进对应的目录，就能直接阅读了，不需要什么高级的展示方法，如果想在网页上阅读，可以看我的网站 https://lvwenhan.com/tech-epic/499.html

好的
